language: php
dist: xenial

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 5.3
      dist: precise
      sudo: true
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --no-interaction

script:
  - composer validate --strict
  - find src examples tests -name '*.php' | xargs -n 1 -P4 php -l
  - vendor/bin/phpunit
